apiVersion: v1
kind: Service
metadata:
    name: "secondkbuckuster-e8f4"
    labels:
        app: "secondkbuckuster-e8f4"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "secondkbuckuster-e8f4"